# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build

on: [push]

jobs:
  build:
    name: 'Build libpng arm64'
    env:
      VCPKG_DISABLE_METRICS: "1"
      VCPKG_ROOT: '${{ github.workspace }}/vcpkg'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    

    - name: Install Arm64 Compiler
      run: sudo apt-get install -qy binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      
    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        TOS="${{ runner.os }}"
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
        echo "build-triplet=arm64-linux.shared" >> "$GITHUB_OUTPUT"

    - name: 'Install vcpkg'
      uses: "./.github/workflows/templates/vcpkg" #Just need to pass the path from action
      with:
        version: 2023.11.20

    - name: 'Install freetype Package'
      run: vcpkg install freetype:${{ steps.strings.outputs.build-triplet }} --overlay-triplets='${{ github.workspace }}/./overlay_trypletes/'

    - name: Upload vcpkg build logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: 'vcpkg-buildlogs-${{ steps.strings.outputs.build-triplet }}'
        path:  /usr/local/share/vcpkg/buildtrees/**/*.log

    - name: 'Export freetype Package'
      run: vcpkg export freetype:${{ steps.strings.outputs.build-triplet }} --zip --output-dir=${{ steps.strings.outputs.build-output-dir }} --overlay-triplets='${{ github.workspace }}/./overlay_trypletes/'     

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
      # Artifact name
        name: Build # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: |
          ${{ steps.strings.outputs.build-output-dir }}/*.zip
        # The desired behavior if no files are found using the provided path.
        
